import type { ApplicationResourceManifest } from "@micro-framework/contracts";
import { scanResource } from "./resource-scan";
import { addDiagnostic, type ScanContext } from "./scan-context";
import type { DeploymentApplicationTarget, DeploymentResourceKind } from "./types";

function isManifest(value: unknown): value is ApplicationResourceManifest {
  if (!value || typeof value !== "object") return false;
  const manifest = value as Partial<ApplicationResourceManifest>;
  return manifest.schemaVersion === 2
    && typeof manifest.application === "string"
    && (manifest.entry === undefined || typeof manifest.entry === "string")
    && Array.isArray(manifest.chunks)
    && Array.isArray(manifest.assets)
    && manifest.chunks.every((chunk) =>
      chunk && typeof chunk.file === "string" && Array.isArray(chunk.imports)
        && Array.isArray(chunk.dynamicImports),
    )
    && manifest.assets.every((asset) => asset && typeof asset.file === "string");
}

function entryKind(application: DeploymentApplicationTarget): DeploymentResourceKind {
  if (application.type === "html") return "entry";
  if (application.type === "module") return "script";
  return /\.(?:mjs|js|jsx|ts|tsx)(?:$|[?#])/i.test(application.entry) ? "script" : "entry";
}

function assetKind(file: string): DeploymentResourceKind {
  if (/\.css(?:$|[?#])/i.test(file)) return "style";
  if (/\.(?:mjs|js|jsx)(?:$|[?#])/i.test(file)) return "script";
  return "asset";
}

export async function runConcurrently<T>(
  values: readonly T[],
  concurrency: number,
  task: (value: T) => Promise<void>,
): Promise<void> {
  let cursor = 0;
  const worker = async () => {
    while (cursor < values.length) {
      const value = values[cursor++];
      if (value !== undefined) await task(value);
    }
  };
  await Promise.all(Array.from({ length: Math.min(concurrency, values.length) }, worker));
}

export async function scanApplication(
  context: ScanContext,
  application: DeploymentApplicationTarget,
): Promise<void> {
  const entryURL = new URL(application.entry, context.hostURL).href;
  const kind = entryKind(application);
  await scanResource(
    context,
    kind,
    entryURL,
    application.name,
    application.integrity,
    kind === "entry",
  );
  if (!application.manifest) return;

  const manifestURL = new URL(application.manifest.url, entryURL).href;
  const manifestResource = await scanResource(
    context,
    "manifest",
    manifestURL,
    application.name,
    application.manifest.integrity,
    true,
  );
  if (!manifestResource.bytes) return;
  let value: unknown;
  try { value = JSON.parse(new TextDecoder().decode(manifestResource.bytes)); }
  catch {
    addDiagnostic(
      context,
      "manifest-invalid",
      "error",
      `Manifest ${manifestURL} is not valid JSON.`,
      "Publish the unmodified schema v2 JSON generated by @micro-framework/vite-plugin.",
      application.name,
      manifestURL,
    );
    return;
  }
  if (!isManifest(value)) {
    addDiagnostic(
      context,
      "manifest-invalid",
      "error",
      `Manifest ${manifestURL} does not match schemaVersion 2.`,
      "Regenerate the manifest with the matching framework Vite plugin version.",
      application.name,
      manifestURL,
    );
    return;
  }

  const resources = [
    ...value.chunks.map((resource) => ({
      kind: "script" as const,
      url: new URL(resource.file, manifestResource.responseURL ?? manifestURL).href,
      integrity: resource.integrity,
    })),
    ...value.assets.map((resource) => ({
      kind: assetKind(resource.file),
      url: new URL(resource.file, manifestResource.responseURL ?? manifestURL).href,
      integrity: resource.integrity,
    })),
  ];
  await runConcurrently(resources, context.options.concurrency, async (resource) => {
    await scanResource(
      context,
      resource.kind,
      resource.url,
      application.name,
      resource.integrity,
      true,
    );
  });
}
